image: golang:1.20-alpine

include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - lint
  - security
  - test

golangci-lint:
  stage: lint
  image: golangci/golangci-lint:v1.53.3
  script:
    - golangci-lint run -v

sast:
  stage: security

test:
  stage: test
  script:
    - CGO_ENABLED=0 go test -coverprofile=coverage.txt -covermode count
    - go tool cover -html=coverage.txt -o=coverage-report.html
    - go tool cover -func=coverage.txt
    - go get github.com/boumenot/gocover-cobertura
    - go run github.com/boumenot/gocover-cobertura < coverage.txt > coverage.xml
    - go install gotest.tools/gotestsum@latest
    - gotestsum --junitfile junit.xml --format testname
  coverage: "/\\(statements\\)\\s+\\d+.?\\d+%/"
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: junit.xml
    paths:
      - coverage-report.html
    expire_in: 7 days
